global:
  storageClass: bahmni-efs-sc

metadata:
  labels:
    environment: dev

bahmni-openmrs:
  enabled: true
bahmni-web:
  enabled: true
bahmni-lab:
  enabled: true
crater:
  enabled: true
reports:
  enabled: true
  config:
    OPENMRS_HOST: "bahmni-openmrs"
  image:
    repository: bahmniindiadistro
    name: reports
    tag: 1.0.0-1
hiu:
  enabled: true
hiu-db:
  enabled: true
  config:
    JAVA_TOOL_OPTIONS: "-Djdbc.url=jdbc:postgresql://bahmni-dev-postgresql:5432/ -Djdbc.username=postgres -Djdbc.password=welcome -Djdbc.database=health_information_user"
hiu-ui:
  enabled: true
  config:
    POSTGRES_HOST: bahmni-dev-postgresql
    RABBITMQ_HOST: bahmni-dev-rabbitmq
hip:
  enabled: true
  config:
    CONNECTION_STRING: "Host=bahmni-dev-postgresql;Port=5432;Username=postgres;Password=welcome;Database=hipservice"
    RABBITMQ_HOST: "bahmni-dev-rabbitmq"
otp-service:
  enabled: true

postgresql:
  enabled: true
  volumePermissions:
    enabled: true
  primary:
    persistence:
      storageClass: bahmni-efs-sc
      accessModes:
        - ReadWriteMany

rabbitmq:
  enabled: true
  auth:
    erlangCookie: bahmni
  persistence:
    storageClass: bahmni-efs-sc
    accessModes:
      - ReadWriteMany

patient-documents:
  enabled: true
  config:
    OPENMRS_HOST: "bahmni-openmrs"