global:
  postgresql:
    auth:
      postgresPassword: welcome

metadata:
  labels:
    environment: local
  ingress:
    PROXY_BODY_SIZE: "7m"
ingress:
  host: bahmni.k8s

openmrs:
  enabled: true
  secrets:
    DB_USERNAME: openmrs-user
    DB_PASSWORD: password
    DB_HOST: mysql
  config:
    DB_NAME: openmrs
bahmni-web:
  enabled: true
bahmni-lab:
  enabled: false
crater:
  enabled: true
  config:
    APP_URL: http://payments-bahmni.local
    DB_DATABASE: crater
    DB_HOST: mysql
    DB_PORT: 3306
    SANCTUM_STATEFUL_DOMAINS: payments-bahmni.local
    SESSION_DOMAIN: payments-bahmni.local
    AUTO_INSTALL: "true"
    ADMIN_NAME: Super Man
    COMPANY_NAME: Bahmni
    COMPANY_SLUG: bahmni
    COUNTRY_ID: 101
  secrets:
    DB_USERNAME: "crater-user"
    DB_PASSWORD: "password"
    ADMIN_EMAIL: "superman@bahmni.org"
    ADMIN_PASSWORD: "crater123"
reports:
  enabled: false
  config:
    OPENMRS_HOST: "openmrs"
    OPENMRS_DB_NAME: openmrs
    REPORTS_DB_NAME: reports
  secrets:
    OPENMRS_DB_HOST: mysql
    OPENMRS_DB_USERNAME: openmrs-user
    OPENMRS_DB_PASSWORD: password
    REPORTS_DB_SERVER: mysql
    REPORTS_DB_USERNAME: reports-user
    REPORTS_DB_PASSWORD: password
hiu:
  enabled: false
  config:
    POSTGRES_HOST: bahmni-local-postgresql
    RABBITMQ_HOST: bahmni-local-rabbitmq
hiu-db:
  enabled: false
  config:
    JAVA_TOOL_OPTIONS: "-Djdbc.url=jdbc:postgresql://bahmni-local-postgresql:5432/ -Djdbc.username=postgres -Djdbc.password=welcome -Djdbc.database=health_information_user"
hiu-ui:
  enabled: false
hip:
  enabled: false
  config:
    CONNECTION_STRING: "Host=bahmni-local-postgresql;Port=5432;Username=postgres;Password=welcome;Database=hipservice"
    RABBITMQ_HOST: "bahmni-local-rabbitmq"
otp-service:
  enabled: false
postgresql:
  enabled: false
rabbit-mq:
  enabled: false
hip-atomfeed:
  enabled: false

rabbitmq:
  auth:
    username: bahmni
    password: bahmni
    erlangCookie: bahmni

patient-documents:
  enabled: true
  config:
    OPENMRS_HOST: "openmrs"

appointments:
  enabled: true

implementer-interface:
  enabled: true