global:
  postgresql:
    auth:
      postgresPassword: welcome

metadata:
  labels:
    environment: local
  ingress:
    PROXY_BODY_SIZE: '7m'
    ABDM_PROXY_BODY_SIZE: '30m'
ingress:
  host: bahmni.k8s

openmrs:
  enabled: true
  secrets:
    OMRS_DB_USERNAME: openmrs-user
    OMRS_DB_PASSWORD: password
    OMRS_DB_HOSTNAME: mysql
  config:
    OMRS_DB_NAME: openmrs
bahmni-web:
  enabled: true
bahmni-lab:
  enabled: true
crater:
  enabled: true
  config:
    APP_URL: http://payments-bahmni.k8s
    DB_DATABASE: crater
    DB_HOST: mysql
    DB_PORT: 3306
    SANCTUM_STATEFUL_DOMAINS: payments-bahmni.k8s
    SESSION_DOMAIN: payments-bahmni.k8s
    AUTO_INSTALL: 'true'
    ADMIN_NAME: Super Man
    COMPANY_NAME: Bahmni
    COMPANY_SLUG: bahmni
    COUNTRY_ID: 101
  secrets:
    DB_USERNAME: 'crater-user'
    DB_PASSWORD: 'password'
    ADMIN_EMAIL: 'superman@bahmni.org'
    ADMIN_PASSWORD: 'crater123'
reports:
  enabled: true
  config:
    OPENMRS_HOST: 'openmrs'
    OPENMRS_DB_NAME: openmrs
    REPORTS_DB_NAME: reports
  secrets:
    OPENMRS_DB_HOST: mysql
    OPENMRS_DB_USERNAME: openmrs-user
    OPENMRS_DB_PASSWORD: password
    REPORTS_DB_SERVER: mysql
    REPORTS_DB_USERNAME: reports-user
    REPORTS_DB_PASSWORD: password
patient-documents:
  enabled: true
  config:
    OPENMRS_HOST: 'openmrs'

appointments:
  enabled: true

crater-atomfeed:
  enabled: true

implementer-interface:
  enabled: true
