apiVersion: v2
name: bahmni-india-distro
description: Helm Umbrella chart for Bahmni India Distribution
type: application
version: 1.0.0

dependencies:
  - repository: https://bahmniindiadistro.github.io/helm-charts
    name: openmrs
    version: ~1.0.0-0
    condition: openmrs.enabled

  - repository: https://bahmniindiadistro.github.io/helm-charts
    name: bahmni-web
    version: ~1.0.0-0
    condition: bahmni-web.enabled

  - repository: https://bahmni.github.io/helm-charts
    name: bahmni-lab
    version: ~1.0.0-0
    condition: bahmni-lab.enabled

  - repository: https://bahmni.github.io/helm-charts
    name: crater
    version: ~1.0.0-0
    condition: crater.enabled

  - repository: https://bahmniindiadistro.github.io/helm-charts
    name: reports
    version: ~1.0.0-0
    condition: reports.enabled

  - repository: https://bahmniindiadistro.github.io/helm-charts
    name: hip
    version: ~1.0.0-0
    condition: hip.enabled

  - repository: https://bahmniindiadistro.github.io/helm-charts
    name: hiu
    version: ~1.0.0-0
    condition: hiu.enabled

  - repository: https://bahmniindiadistro.github.io/helm-charts
    name: hiu-db
    version: ~1.0.0-0
    condition: hiu-db.enabled

  - repository: https://bahmniindiadistro.github.io/helm-charts
    name: hiu-ui
    version: ~1.0.0-0
    condition: hiu-ui.enabled

  - repository: https://bahmniindiadistro.github.io/helm-charts
    name: otp-service
    version: ~1.0.0-0
    condition: otp-service.enabled

  - repository: https://charts.bitnami.com/bitnami
    name: postgresql
    version: 11.2.6
    condition: postgresql.enabled

  - repository: https://charts.bitnami.com/bitnami
    name: rabbitmq
    version: 9.1.4
    condition: rabbitmq.enabled

  - repository: https://bahmni.github.io/helm-charts
    name: patient-documents
    version: ~1.0.0-0
    condition: patient-documents.enabled

  - repository: https://bahmniindiadistro.github.io/helm-charts
    name: hip-atomfeed
    version: ~1.0.0-0
    condition: hip-atomfeed.enabled

  - repository: https://bahmni.github.io/helm-charts
    name: appointments
    version: ~1.0.0-0
    condition: appointments.enabled
